package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AreaId generated by hbm2java
 */
@Embeddable
public class AreaId  implements java.io.Serializable {


     private int id;
     private int unidadeId;

    public AreaId() {
    }

    public AreaId(int id, int unidadeId) {
       this.id = id;
       this.unidadeId = unidadeId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="unidade_id", nullable=false)
    public int getUnidadeId() {
        return this.unidadeId;
    }
    
    public void setUnidadeId(int unidadeId) {
        this.unidadeId = unidadeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AreaId) ) return false;
		 AreaId castOther = ( AreaId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getUnidadeId()==castOther.getUnidadeId());
   }
   
     @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getUnidadeId();
         return result;
   }   


}


