package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name="area"
    ,catalog="ocorrencia"
)
public class Area  implements java.io.Serializable {


     private AreaId id;
     private Unidade unidade;
     private String compania;
     private Set subareas = new HashSet(0);

    public Area() {
    }

	
    public Area(AreaId id, Unidade unidade) {
        this.id = id;
        this.unidade = unidade;
    }
    public Area(AreaId id, Unidade unidade, String compania, Set subareas) {
       this.id = id;
       this.unidade = unidade;
       this.compania = compania;
       this.subareas = subareas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="unidadeId", column=@Column(name="unidade_id", nullable=false) ) } )
    public AreaId getId() {
        return this.id;
    }
    
    public void setId(AreaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unidade_id", nullable=false, insertable=false, updatable=false)
    public Unidade getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(Unidade unidade) {
        this.unidade = unidade;
    }

    
    @Column(name="compania", length=45)
    public String getCompania() {
        return this.compania;
    }
    
    public void setCompania(String compania) {
        this.compania = compania;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="area")
    public Set getSubareas() {
        return this.subareas;
    }
    
    public void setSubareas(Set subareas) {
        this.subareas = subareas;
    }




}


