package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AtendimentoId generated by hbm2java
 */
@Embeddable
public class AtendimentoId  implements java.io.Serializable {


     private int protocolo;
     private int dadosId;

    public AtendimentoId() {
    }

    public AtendimentoId(int protocolo, int dadosId) {
       this.protocolo = protocolo;
       this.dadosId = dadosId;
    }
   


    @Column(name="protocolo", nullable=false)
    public int getProtocolo() {
        return this.protocolo;
    }
    
    public void setProtocolo(int protocolo) {
        this.protocolo = protocolo;
    }


    @Column(name="dados_id", nullable=false)
    public int getDadosId() {
        return this.dadosId;
    }
    
    public void setDadosId(int dadosId) {
        this.dadosId = dadosId;
    }


     @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AtendimentoId) ) return false;
		 AtendimentoId castOther = ( AtendimentoId ) other; 
         
		 return (this.getProtocolo()==castOther.getProtocolo())
 && (this.getDadosId()==castOther.getDadosId());
   }
   
     @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProtocolo();
         result = 37 * result + this.getDadosId();
         return result;
   }   


}


