package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CidadeId generated by hbm2java
 */
@Embeddable
public class CidadeId  implements java.io.Serializable {


     private int id;
     private int estadoId;
     private int estadoPaisId;

    public CidadeId() {
    }

    public CidadeId(int id, int estadoId, int estadoPaisId) {
       this.id = id;
       this.estadoId = estadoId;
       this.estadoPaisId = estadoPaisId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="estado_id", nullable=false)
    public int getEstadoId() {
        return this.estadoId;
    }
    
    public void setEstadoId(int estadoId) {
        this.estadoId = estadoId;
    }


    @Column(name="estado_pais_id", nullable=false)
    public int getEstadoPaisId() {
        return this.estadoPaisId;
    }
    
    public void setEstadoPaisId(int estadoPaisId) {
        this.estadoPaisId = estadoPaisId;
    }


     @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CidadeId) ) return false;
		 CidadeId castOther = ( CidadeId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getEstadoId()==castOther.getEstadoId())
 && (this.getEstadoPaisId()==castOther.getEstadoPaisId());
   }
   
     @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getEstadoId();
         result = 37 * result + this.getEstadoPaisId();
         return result;
   }   


}


