package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,catalog="ocorrencia"
)
public class Cidade  implements java.io.Serializable {


     private CidadeId id;
     private Estado estado;
     private String nome;
     private Set veiculos = new HashSet(0);
     private Set enderecos = new HashSet(0);
     private Set naturalidades = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(CidadeId id, Estado estado, String nome) {
        this.id = id;
        this.estado = estado;
        this.nome = nome;
    }
    public Cidade(CidadeId id, Estado estado, String nome, Set veiculos, Set enderecos, Set naturalidades) {
       this.id = id;
       this.estado = estado;
       this.nome = nome;
       this.veiculos = veiculos;
       this.enderecos = enderecos;
       this.naturalidades = naturalidades;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="estadoId", column=@Column(name="estado_id", nullable=false) ), 
        @AttributeOverride(name="estadoPaisId", column=@Column(name="estado_pais_id", nullable=false) ) } )
    public CidadeId getId() {
        return this.id;
    }
    
    public void setId(CidadeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="estado_id", referencedColumnName="id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="estado_pais_id", referencedColumnName="pais_id", nullable=false, insertable=false, updatable=false) } )
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    
    @Column(name="nome", nullable=false, length=120)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set getVeiculos() {
        return this.veiculos;
    }
    
    public void setVeiculos(Set veiculos) {
        this.veiculos = veiculos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set getNaturalidades() {
        return this.naturalidades;
    }
    
    public void setNaturalidades(Set naturalidades) {
        this.naturalidades = naturalidades;
    }




}


