package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Compnente generated by hbm2java
 */
@Entity
@Table(name="compnente"
    ,catalog="ocorrencia"
)
public class Compnente  implements java.io.Serializable {


     private int militarMatricula;
     private Militar militar;
     private String funcao;

    public Compnente() {
    }

    public Compnente(Militar militar, String funcao) {
       this.militar = militar;
       this.funcao = funcao;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="militar"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="militar_matricula", unique=true, nullable=false)
    public int getMilitarMatricula() {
        return this.militarMatricula;
    }
    
    public void setMilitarMatricula(int militarMatricula) {
        this.militarMatricula = militarMatricula;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Militar getMilitar() {
        return this.militar;
    }
    
    public void setMilitar(Militar militar) {
        this.militar = militar;
    }

    
    @Column(name="funcao", nullable=false, length=45)
    public String getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }




}


