package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contato generated by hbm2java
 */
@Entity
@Table(name="contato"
    ,catalog="ocorrencia"
)
public class Contato  implements java.io.Serializable {


     private Integer id;
     private String celular;
     private String celular1;
     private String fixo;
     private String email;
     private Set envolvidos = new HashSet(0);

    public Contato() {
    }

    public Contato(String celular, String celular1, String fixo, String email, Set envolvidos) {
       this.celular = celular;
       this.celular1 = celular1;
       this.fixo = fixo;
       this.email = email;
       this.envolvidos = envolvidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="celular", length=18)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="celular1", length=18)
    public String getCelular1() {
        return this.celular1;
    }
    
    public void setCelular1(String celular1) {
        this.celular1 = celular1;
    }

    
    @Column(name="fixo", length=18)
    public String getFixo() {
        return this.fixo;
    }
    
    public void setFixo(String fixo) {
        this.fixo = fixo;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contato")
    public Set getEnvolvidos() {
        return this.envolvidos;
    }
    
    public void setEnvolvidos(Set envolvidos) {
        this.envolvidos = envolvidos;
    }




}


