package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dados generated by hbm2java
 */
@Entity
@Table(name="dados"
    ,catalog="ocorrencia"
)
public class Dados  implements java.io.Serializable {


     private Integer id;
     private Date data;
     private Date hora;
     private String area;
     private Boolean policialenvolvido;
     private Boolean autoridadeenvolvida;
     private Boolean apreensdeaoarma;
     private Boolean apreensdeentorpecentes;
     private Boolean flagrante;
     private Boolean tco;
     private Boolean bco;
     private Set atendimentos = new HashSet(0);

    public Dados() {
    }

	
    public Dados(Date data, Date hora) {
        this.data = data;
        this.hora = hora;
    }
    public Dados(Date data, Date hora, String area, Boolean policialenvolvido, Boolean autoridadeenvolvida, Boolean apreensdeaoarma, Boolean apreensdeentorpecentes, Boolean flagrante, Boolean tco, Boolean bco, Set atendimentos) {
       this.data = data;
       this.hora = hora;
       this.area = area;
       this.policialenvolvido = policialenvolvido;
       this.autoridadeenvolvida = autoridadeenvolvida;
       this.apreensdeaoarma = apreensdeaoarma;
       this.apreensdeentorpecentes = apreensdeentorpecentes;
       this.flagrante = flagrante;
       this.tco = tco;
       this.bco = bco;
       this.atendimentos = atendimentos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data", nullable=false, length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="hora", nullable=false, length=19)
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }

    
    @Column(name="area", length=50)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="policialenvolvido")
    public Boolean getPolicialenvolvido() {
        return this.policialenvolvido;
    }
    
    public void setPolicialenvolvido(Boolean policialenvolvido) {
        this.policialenvolvido = policialenvolvido;
    }

    
    @Column(name="autoridadeenvolvida")
    public Boolean getAutoridadeenvolvida() {
        return this.autoridadeenvolvida;
    }
    
    public void setAutoridadeenvolvida(Boolean autoridadeenvolvida) {
        this.autoridadeenvolvida = autoridadeenvolvida;
    }

    
    @Column(name="apreensdeaoarma")
    public Boolean getApreensdeaoarma() {
        return this.apreensdeaoarma;
    }
    
    public void setApreensdeaoarma(Boolean apreensdeaoarma) {
        this.apreensdeaoarma = apreensdeaoarma;
    }

    
    @Column(name="apreensdeentorpecentes")
    public Boolean getApreensdeentorpecentes() {
        return this.apreensdeentorpecentes;
    }
    
    public void setApreensdeentorpecentes(Boolean apreensdeentorpecentes) {
        this.apreensdeentorpecentes = apreensdeentorpecentes;
    }

    
    @Column(name="flagrante")
    public Boolean getFlagrante() {
        return this.flagrante;
    }
    
    public void setFlagrante(Boolean flagrante) {
        this.flagrante = flagrante;
    }

    
    @Column(name="tco")
    public Boolean getTco() {
        return this.tco;
    }
    
    public void setTco(Boolean tco) {
        this.tco = tco;
    }

    
    @Column(name="bco")
    public Boolean getBco() {
        return this.bco;
    }
    
    public void setBco(Boolean bco) {
        this.bco = bco;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dados")
    public Set getAtendimentos() {
        return this.atendimentos;
    }
    
    public void setAtendimentos(Set atendimentos) {
        this.atendimentos = atendimentos;
    }




}


