package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dpm generated by hbm2java
 */
@Entity
@Table(name="dpm"
    ,catalog="ocorrencia"
)
public class Dpm  implements java.io.Serializable {


     private DpmId id;
     private Subarea subarea;
     private String dpm;

    public Dpm() {
    }

	
    public Dpm(DpmId id, Subarea subarea) {
        this.id = id;
        this.subarea = subarea;
    }
    public Dpm(DpmId id, Subarea subarea, String dpm) {
       this.id = id;
       this.subarea = subarea;
       this.dpm = dpm;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="subareaId", column=@Column(name="subarea_id", nullable=false) ), 
        @AttributeOverride(name="subareaAreaId", column=@Column(name="subarea_area_id", nullable=false) ), 
        @AttributeOverride(name="subareaAreaUnidadeId", column=@Column(name="subarea_area_unidade_id", nullable=false) ) } )
    public DpmId getId() {
        return this.id;
    }
    
    public void setId(DpmId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="subarea_id", referencedColumnName="id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="subarea_area_id", referencedColumnName="area_id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="subarea_area_unidade_id", referencedColumnName="area_unidade_id", nullable=false, insertable=false, updatable=false) } )
    public Subarea getSubarea() {
        return this.subarea;
    }
    
    public void setSubarea(Subarea subarea) {
        this.subarea = subarea;
    }

    
    @Column(name="dpm", length=45)
    public String getDpm() {
        return this.dpm;
    }
    
    public void setDpm(String dpm) {
        this.dpm = dpm;
    }




}


