package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DpmId generated by hbm2java
 */
@Embeddable
public class DpmId  implements java.io.Serializable {


     private int id;
     private int subareaId;
     private int subareaAreaId;
     private int subareaAreaUnidadeId;

    public DpmId() {
    }

    public DpmId(int id, int subareaId, int subareaAreaId, int subareaAreaUnidadeId) {
       this.id = id;
       this.subareaId = subareaId;
       this.subareaAreaId = subareaAreaId;
       this.subareaAreaUnidadeId = subareaAreaUnidadeId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="subarea_id", nullable=false)
    public int getSubareaId() {
        return this.subareaId;
    }
    
    public void setSubareaId(int subareaId) {
        this.subareaId = subareaId;
    }


    @Column(name="subarea_area_id", nullable=false)
    public int getSubareaAreaId() {
        return this.subareaAreaId;
    }
    
    public void setSubareaAreaId(int subareaAreaId) {
        this.subareaAreaId = subareaAreaId;
    }


    @Column(name="subarea_area_unidade_id", nullable=false)
    public int getSubareaAreaUnidadeId() {
        return this.subareaAreaUnidadeId;
    }
    
    public void setSubareaAreaUnidadeId(int subareaAreaUnidadeId) {
        this.subareaAreaUnidadeId = subareaAreaUnidadeId;
    }


     @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DpmId) ) return false;
		 DpmId castOther = ( DpmId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getSubareaId()==castOther.getSubareaId())
 && (this.getSubareaAreaId()==castOther.getSubareaAreaId())
 && (this.getSubareaAreaUnidadeId()==castOther.getSubareaAreaUnidadeId());
   }
   
     @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getSubareaId();
         result = 37 * result + this.getSubareaAreaId();
         result = 37 * result + this.getSubareaAreaUnidadeId();
         return result;
   }   


}


