package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnderecoId generated by hbm2java
 */
@Embeddable
public class EnderecoId  implements java.io.Serializable {


     private int id;
     private int cidadeId;
     private int cidadeEstadoId;
     private int cidadeEstadoPaisId;

    public EnderecoId() {
    }

    public EnderecoId(int id, int cidadeId, int cidadeEstadoId, int cidadeEstadoPaisId) {
       this.id = id;
       this.cidadeId = cidadeId;
       this.cidadeEstadoId = cidadeEstadoId;
       this.cidadeEstadoPaisId = cidadeEstadoPaisId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="cidade_id", nullable=false)
    public int getCidadeId() {
        return this.cidadeId;
    }
    
    public void setCidadeId(int cidadeId) {
        this.cidadeId = cidadeId;
    }


    @Column(name="cidade_estado_id", nullable=false)
    public int getCidadeEstadoId() {
        return this.cidadeEstadoId;
    }
    
    public void setCidadeEstadoId(int cidadeEstadoId) {
        this.cidadeEstadoId = cidadeEstadoId;
    }


    @Column(name="cidade_estado_pais_id", nullable=false)
    public int getCidadeEstadoPaisId() {
        return this.cidadeEstadoPaisId;
    }
    
    public void setCidadeEstadoPaisId(int cidadeEstadoPaisId) {
        this.cidadeEstadoPaisId = cidadeEstadoPaisId;
    }


     @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnderecoId) ) return false;
		 EnderecoId castOther = ( EnderecoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCidadeId()==castOther.getCidadeId())
 && (this.getCidadeEstadoId()==castOther.getCidadeEstadoId())
 && (this.getCidadeEstadoPaisId()==castOther.getCidadeEstadoPaisId());
   }
   
     @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCidadeId();
         result = 37 * result + this.getCidadeEstadoId();
         result = 37 * result + this.getCidadeEstadoPaisId();
         return result;
   }   


}


