package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Envolvido generated by hbm2java
 */
@Entity
@Table(name="envolvido"
    ,catalog="ocorrencia"
)
public class Envolvido  implements java.io.Serializable {


     private EnvolvidoId id;
     private Contato contato;
     private Endereco endereco;
     private Qualificacao qualificacao;
     private String nome;
     private String apelido;
     private String sexo;
     private Date dtNascimento;
     private String identidade;
     private String orgao;
     private String cpf;
     private String pai;
     private String mae;
     private String cor;
     private String estadoCivil;
     private String rg;
     private String profissao;
     private String localTrabalho;
     private Boolean anonimo;
     
    //Naturalidade e nacionalidade
    private String cidadeNatal;

    private String ufNatal;

    private String paisNatal;

    //Endereço
    private String logradouro;

    private Integer numero;

    private String cidade;

    private String referencia;//= ao campo complemento no banco

    private String uf;

    private String pais;

    private String cep;

    //Contato
    private String celular;

    private String celular1;

    private String fixo;

    private String inforadiciona;
    
    //@Pattern(regexp = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$")
    private String email;

    public Envolvido() {
    }

	
    public Envolvido(EnvolvidoId id, Contato contato, Endereco endereco, Qualificacao qualificacao, String nome, String sexo) {
        this.id = id;
        this.contato = contato;
        this.endereco = endereco;
        this.qualificacao = qualificacao;
        this.nome = nome;
        this.sexo = sexo;
    }
    public Envolvido(EnvolvidoId id, Contato contato, Endereco endereco, Qualificacao qualificacao, String nome, String sexo, Date dtNascimento, String identidade, String orgao, String pai, String mae, String cor, String estadoCivil, String profissao, String localTrabalho, Boolean anonimo) {
       this.id = id;
       this.contato = contato;
       this.endereco = endereco;
       this.qualificacao = qualificacao;
       this.nome = nome;
       this.sexo = sexo;
       this.dtNascimento = dtNascimento;
       this.identidade = identidade;
       this.orgao = orgao;
       this.pai = pai;
       this.mae = mae;
       this.cor = cor;
       this.estadoCivil = estadoCivil;
       this.profissao = profissao;
       this.localTrabalho = localTrabalho;
       this.anonimo = anonimo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="contatoId", column=@Column(name="contato_id", nullable=false) ), 
        @AttributeOverride(name="qualificacaoId", column=@Column(name="qualificacao_id", nullable=false) ) } )
    public EnvolvidoId getId() {
        return this.id;
    }
    
    public void setId(EnvolvidoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contato_id", nullable=false, insertable=false, updatable=false)
    public Contato getContato() {
        return this.contato;
    }
    
    public void setContato(Contato contato) {
        this.contato = contato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="endereco_id", referencedColumnName="id", nullable=false), 
        @JoinColumn(name="endereco_cidade_id", referencedColumnName="cidade_id", nullable=false), 
        @JoinColumn(name="endereco_cidade_estado_id", referencedColumnName="cidade_estado_id", nullable=false), 
        @JoinColumn(name="endereco_cidade_estado_pais_id", referencedColumnName="cidade_estado_pais_id", nullable=false) } )
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="qualificacao_id", nullable=false, insertable=false, updatable=false)
    public Qualificacao getQualificacao() {
        return this.qualificacao;
    }
    
    public void setQualificacao(Qualificacao qualificacao) {
        this.qualificacao = qualificacao;
    }

    
    @Column(name="nome", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sexo", nullable=false)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="nascimento", length=19)
    public Date getDtNascimento() {
        return this.dtNascimento;
    }
    
    public void setDtNascimento(Date dtNascimento) {
        this.dtNascimento = dtNascimento;
    }

    
    @Column(name="identidade", length=50)
    public String getIdentidade() {
        return this.identidade;
    }
    
    public void setIdentidade(String identidade) {
        this.identidade = identidade;
    }

    
    @Column(name="orgao", length=50)
    public String getOrgao() {
        return this.orgao;
    }
    
    public void setOrgao(String orgao) {
        this.orgao = orgao;
    }

    
    @Column(name="pai", length=50)
    public String getPai() {
        return this.pai;
    }
    
    public void setPai(String pai) {
        this.pai = pai;
    }

    
    @Column(name="mae", length=50)
    public String getMae() {
        return this.mae;
    }
    
    public void setMae(String mae) {
        this.mae = mae;
    }

    
    @Column(name="cor", length=50)
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }

    
    @Column(name="estado_civil", length=50)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    
    @Column(name="profissao", length=50)
    public String getProfissao() {
        return this.profissao;
    }
    
    public void setProfissao(String profissao) {
        this.profissao = profissao;
    }

    
    @Column(name="local_trabalho", length=50)
    public String getLocalTrabalho() {
        return this.localTrabalho;
    }
    
    public void setLocalTrabalho(String localTrabalho) {
        this.localTrabalho = localTrabalho;
    }

    
    @Column(name="anonimo")
    public Boolean getAnonimo() {
        return this.anonimo;
    }
    
    public void setAnonimo(Boolean anonimo) {
        this.anonimo = anonimo;
    }

    public String getApelido() {
        return apelido;
    }

    public void setApelido(String apelido) {
        this.apelido = apelido;
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public String getCidadeNatal() {
        return cidadeNatal;
    }

    public void setCidadeNatal(String cidadeNatal) {
        this.cidadeNatal = cidadeNatal;
    }

    public String getUfNatal() {
        return ufNatal;
    }

    public void setUfNatal(String ufNatal) {
        this.ufNatal = ufNatal;
    }

    public String getPaisNatal() {
        return paisNatal;
    }

    public void setPaisNatal(String paisNatal) {
        this.paisNatal = paisNatal;
    }

    public String getLogradouro() {
        return logradouro;
    }

    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    public String getCidade() {
        return cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public String getReferencia() {
        return referencia;
    }

    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    public String getUf() {
        return uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    public String getPais() {
        return pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    public String getCep() {
        return cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    public String getCelular() {
        return celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    public String getCelular1() {
        return celular1;
    }

    public void setCelular1(String celular1) {
        this.celular1 = celular1;
    }

    public String getFixo() {
        return fixo;
    }

    public void setFixo(String fixo) {
        this.fixo = fixo;
    }

    public String getInforadiciona() {
        return inforadiciona;
    }

    public void setInforadiciona(String inforadiciona) {
        this.inforadiciona = inforadiciona;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getRg() {
        return rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }




}


