package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="estado"
    ,catalog="ocorrencia"
)
public class Estado  implements java.io.Serializable {


     private EstadoId id;
     private Pais pais;
     private String nome;
     private String sigla;
     private Set cidades = new HashSet(0);

    public Estado() {
    }

	
    public Estado(EstadoId id, Pais pais, String nome, String sigla) {
        this.id = id;
        this.pais = pais;
        this.nome = nome;
        this.sigla = sigla;
    }
    public Estado(EstadoId id, Pais pais, String nome, String sigla, Set cidades) {
       this.id = id;
       this.pais = pais;
       this.nome = nome;
       this.sigla = sigla;
       this.cidades = cidades;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="paisId", column=@Column(name="pais_id", nullable=false) ) } )
    public EstadoId getId() {
        return this.id;
    }
    
    public void setId(EstadoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pais_id", nullable=false, insertable=false, updatable=false)
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }

    
    @Column(name="nome", nullable=false, length=75)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sigla", nullable=false, length=5)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


