package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Historico generated by hbm2java
 */
@Entity
@Table(name="historico"
    ,catalog="ocorrencia"
)
public class Historico  implements java.io.Serializable {


     private Integer id;
     private String historico;
     private Set registros = new HashSet(0);

    public Historico() {
    }

	
    public Historico(String historico) {
        this.historico = historico;
    }
    public Historico(String historico, Set registros) {
       this.historico = historico;
       this.registros = registros;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="historico", nullable=false, length=8000)
    public String getHistorico() {
        return this.historico;
    }
    
    public void setHistorico(String historico) {
        this.historico = historico;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="historico")
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


