package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Militar generated by hbm2java
 */
@Entity
@Table(name="militar"
    ,catalog="ocorrencia"
)
public class Militar  implements java.io.Serializable {


     private int matricula;
     private String rg;
     private String nome;
     private String graduacao;
     private Compnente compnente;

    public Militar() {
    }

	
    public Militar(int matricula, String rg, String nome, String graduacao) {
        this.matricula = matricula;
        this.rg = rg;
        this.nome = nome;
        this.graduacao = graduacao;
    }
    public Militar(int matricula, String rg, String nome, String graduacao, Compnente compnente) {
       this.matricula = matricula;
       this.rg = rg;
       this.nome = nome;
       this.graduacao = graduacao;
       this.compnente = compnente;
    }
   
     @Id 

    
    @Column(name="matricula", unique=true, nullable=false)
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }

    
    @Column(name="rg", nullable=false, length=45)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="graduacao", nullable=false, length=45)
    public String getGraduacao() {
        return this.graduacao;
    }
    
    public void setGraduacao(String graduacao) {
        this.graduacao = graduacao;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="militar")
    public Compnente getCompnente() {
        return this.compnente;
    }
    
    public void setCompnente(Compnente compnente) {
        this.compnente = compnente;
    }




}


