package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,catalog="ocorrencia"
)
public class Pais  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String sigla;
     private Set estados = new HashSet(0);

    public Pais() {
    }

	
    public Pais(String nome, String sigla) {
        this.nome = nome;
        this.sigla = sigla;
    }
    public Pais(String nome, String sigla, Set estados) {
       this.nome = nome;
       this.sigla = sigla;
       this.estados = estados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=60)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sigla", nullable=false, length=10)
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
    public Set getEstados() {
        return this.estados;
    }
    
    public void setEstados(Set estados) {
        this.estados = estados;
    }




}


