package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Qualificacao generated by hbm2java
 */
@Entity
@Table(name="qualificacao"
    ,catalog="ocorrencia"
)
public class Qualificacao  implements java.io.Serializable {


     private Integer id;
     private Boolean acusado;
     private Boolean vitima;
     private Boolean atendido;
     private Boolean assistido;
     private Boolean solicitante;
     private Boolean testemunha;
     private Boolean denucinante;
     private Boolean comunicante;
     private Boolean acidentado;
     private Boolean condutor;
     private Boolean passageiro;
     private Boolean suspeito;
     private Boolean desaparecido;
     private Boolean proprietario;
     private String conduzido;
     private Set envolvidos = new HashSet(0);

    public Qualificacao() {
    }

    public Qualificacao(Boolean acusado, Boolean vitima, Boolean atendido, Boolean assistido, Boolean solicitante, Boolean testemunha, Boolean denucinante, Boolean comunicante, Boolean acidentado, Boolean condutor, Boolean passageiro, Boolean suspeito, Boolean desaparecido, Boolean proprietario, String conduzido, Set envolvidos) {
       this.acusado = acusado;
       this.vitima = vitima;
       this.atendido = atendido;
       this.assistido = assistido;
       this.solicitante = solicitante;
       this.testemunha = testemunha;
       this.denucinante = denucinante;
       this.comunicante = comunicante;
       this.acidentado = acidentado;
       this.condutor = condutor;
       this.passageiro = passageiro;
       this.suspeito = suspeito;
       this.desaparecido = desaparecido;
       this.proprietario = proprietario;
       this.conduzido = conduzido;
       this.envolvidos = envolvidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="acusado")
    public Boolean getAcusado() {
        return this.acusado;
    }
    
    public void setAcusado(Boolean acusado) {
        this.acusado = acusado;
    }

    
    @Column(name="vitima")
    public Boolean getVitima() {
        return this.vitima;
    }
    
    public void setVitima(Boolean vitima) {
        this.vitima = vitima;
    }

    
    @Column(name="atendido")
    public Boolean getAtendido() {
        return this.atendido;
    }
    
    public void setAtendido(Boolean atendido) {
        this.atendido = atendido;
    }

    
    @Column(name="assistido")
    public Boolean getAssistido() {
        return this.assistido;
    }
    
    public void setAssistido(Boolean assistido) {
        this.assistido = assistido;
    }

    
    @Column(name="solicitante")
    public Boolean getSolicitante() {
        return this.solicitante;
    }
    
    public void setSolicitante(Boolean solicitante) {
        this.solicitante = solicitante;
    }

    
    @Column(name="testemunha")
    public Boolean getTestemunha() {
        return this.testemunha;
    }
    
    public void setTestemunha(Boolean testemunha) {
        this.testemunha = testemunha;
    }

    
    @Column(name="denucinante")
    public Boolean getDenucinante() {
        return this.denucinante;
    }
    
    public void setDenucinante(Boolean denucinante) {
        this.denucinante = denucinante;
    }

    
    @Column(name="comunicante")
    public Boolean getComunicante() {
        return this.comunicante;
    }
    
    public void setComunicante(Boolean comunicante) {
        this.comunicante = comunicante;
    }

    
    @Column(name="acidentado")
    public Boolean getAcidentado() {
        return this.acidentado;
    }
    
    public void setAcidentado(Boolean acidentado) {
        this.acidentado = acidentado;
    }

    
    @Column(name="condutor")
    public Boolean getCondutor() {
        return this.condutor;
    }
    
    public void setCondutor(Boolean condutor) {
        this.condutor = condutor;
    }

    
    @Column(name="passageiro")
    public Boolean getPassageiro() {
        return this.passageiro;
    }
    
    public void setPassageiro(Boolean passageiro) {
        this.passageiro = passageiro;
    }

    
    @Column(name="suspeito")
    public Boolean getSuspeito() {
        return this.suspeito;
    }
    
    public void setSuspeito(Boolean suspeito) {
        this.suspeito = suspeito;
    }

    
    @Column(name="desaparecido")
    public Boolean getDesaparecido() {
        return this.desaparecido;
    }
    
    public void setDesaparecido(Boolean desaparecido) {
        this.desaparecido = desaparecido;
    }

    
    @Column(name="proprietario")
    public Boolean getProprietario() {
        return this.proprietario;
    }
    
    public void setProprietario(Boolean proprietario) {
        this.proprietario = proprietario;
    }

    
    @Column(name="conduzido", length=45)
    public String getConduzido() {
        return this.conduzido;
    }
    
    public void setConduzido(String conduzido) {
        this.conduzido = conduzido;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="qualificacao")
    public Set getEnvolvidos() {
        return this.envolvidos;
    }
    
    public void setEnvolvidos(Set envolvidos) {
        this.envolvidos = envolvidos;
    }




}


