package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Registro generated by hbm2java
 */
@Entity
@Table(name="registro"
    ,catalog="ocorrencia"
)
public class Registro  implements java.io.Serializable {


     private RegistroId id;
     private Atendimento atendimento;
     private Historico historico;
     private Vtr vtr;

    public Registro() {
    }

    public Registro(RegistroId id, Atendimento atendimento, Historico historico, Vtr vtr) {
       this.id = id;
       this.atendimento = atendimento;
       this.historico = historico;
       this.vtr = vtr;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="naturezaId", column=@Column(name="natureza_id", nullable=false) ), 
        @AttributeOverride(name="naturezaGrupoId", column=@Column(name="natureza_grupo_id", nullable=false) ), 
        @AttributeOverride(name="historicoId", column=@Column(name="historico_id", nullable=false) ), 
        @AttributeOverride(name="vtrId", column=@Column(name="vtr_id", nullable=false) ) } )
    public RegistroId getId() {
        return this.id;
    }
    
    public void setId(RegistroId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="atendimento_protocolo", referencedColumnName="protocolo", nullable=false), 
        @JoinColumn(name="atendimento_dados_id", referencedColumnName="dados_id", nullable=false) } )
    public Atendimento getAtendimento() {
        return this.atendimento;
    }
    
    public void setAtendimento(Atendimento atendimento) {
        this.atendimento = atendimento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="historico_id", nullable=false, insertable=false, updatable=false)
    public Historico getHistorico() {
        return this.historico;
    }
    
    public void setHistorico(Historico historico) {
        this.historico = historico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vtr_id", nullable=false, insertable=false, updatable=false)
    public Vtr getVtr() {
        return this.vtr;
    }
    
    public void setVtr(Vtr vtr) {
        this.vtr = vtr;
    }




}


