package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegistroId generated by hbm2java
 */
@Embeddable
public class RegistroId  implements java.io.Serializable {


     private int id;
     private int naturezaId;
     private int naturezaGrupoId;
     private int historicoId;
     private int vtrId;

    public RegistroId() {
    }

    public RegistroId(int id, int naturezaId, int naturezaGrupoId, int historicoId, int vtrId) {
       this.id = id;
       this.naturezaId = naturezaId;
       this.naturezaGrupoId = naturezaGrupoId;
       this.historicoId = historicoId;
       this.vtrId = vtrId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="natureza_id", nullable=false)
    public int getNaturezaId() {
        return this.naturezaId;
    }
    
    public void setNaturezaId(int naturezaId) {
        this.naturezaId = naturezaId;
    }


    @Column(name="natureza_grupo_id", nullable=false)
    public int getNaturezaGrupoId() {
        return this.naturezaGrupoId;
    }
    
    public void setNaturezaGrupoId(int naturezaGrupoId) {
        this.naturezaGrupoId = naturezaGrupoId;
    }


    @Column(name="historico_id", nullable=false)
    public int getHistoricoId() {
        return this.historicoId;
    }
    
    public void setHistoricoId(int historicoId) {
        this.historicoId = historicoId;
    }


    @Column(name="vtr_id", nullable=false)
    public int getVtrId() {
        return this.vtrId;
    }
    
    public void setVtrId(int vtrId) {
        this.vtrId = vtrId;
    }


     @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RegistroId) ) return false;
		 RegistroId castOther = ( RegistroId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getNaturezaId()==castOther.getNaturezaId())
 && (this.getNaturezaGrupoId()==castOther.getNaturezaGrupoId())
 && (this.getHistoricoId()==castOther.getHistoricoId())
 && (this.getVtrId()==castOther.getVtrId());
   }
   
     @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getNaturezaId();
         result = 37 * result + this.getNaturezaGrupoId();
         result = 37 * result + this.getHistoricoId();
         result = 37 * result + this.getVtrId();
         return result;
   }   


}


