package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subarea generated by hbm2java
 */
@Entity
@Table(name="subarea"
    ,catalog="ocorrencia"
)
public class Subarea  implements java.io.Serializable {


     private SubareaId id;
     private Area area;
     private String pelotao;
     private Set dpms = new HashSet(0);

    public Subarea() {
    }

	
    public Subarea(SubareaId id, Area area) {
        this.id = id;
        this.area = area;
    }
    public Subarea(SubareaId id, Area area, String pelotao, Set dpms) {
       this.id = id;
       this.area = area;
       this.pelotao = pelotao;
       this.dpms = dpms;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="areaId", column=@Column(name="area_id", nullable=false) ), 
        @AttributeOverride(name="areaUnidadeId", column=@Column(name="area_unidade_id", nullable=false) ) } )
    public SubareaId getId() {
        return this.id;
    }
    
    public void setId(SubareaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="area_id", referencedColumnName="id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="area_unidade_id", referencedColumnName="unidade_id", nullable=false, insertable=false, updatable=false) } )
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }

    
    @Column(name="pelotao", length=45)
    public String getPelotao() {
        return this.pelotao;
    }
    
    public void setPelotao(String pelotao) {
        this.pelotao = pelotao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subarea")
    public Set getDpms() {
        return this.dpms;
    }
    
    public void setDpms(Set dpms) {
        this.dpms = dpms;
    }




}


