package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubareaId generated by hbm2java
 */
@Embeddable
public class SubareaId  implements java.io.Serializable {


     private int id;
     private int areaId;
     private int areaUnidadeId;

    public SubareaId() {
    }

    public SubareaId(int id, int areaId, int areaUnidadeId) {
       this.id = id;
       this.areaId = areaId;
       this.areaUnidadeId = areaUnidadeId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="area_id", nullable=false)
    public int getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }


    @Column(name="area_unidade_id", nullable=false)
    public int getAreaUnidadeId() {
        return this.areaUnidadeId;
    }
    
    public void setAreaUnidadeId(int areaUnidadeId) {
        this.areaUnidadeId = areaUnidadeId;
    }


     @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubareaId) ) return false;
		 SubareaId castOther = ( SubareaId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getAreaId()==castOther.getAreaId())
 && (this.getAreaUnidadeId()==castOther.getAreaUnidadeId());
   }
   
     @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getAreaId();
         result = 37 * result + this.getAreaUnidadeId();
         return result;
   }   


}


