package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unidade generated by hbm2java
 */
@Entity
@Table(name="unidade"
    ,catalog="ocorrencia"
)
public class Unidade  implements java.io.Serializable {


     private Integer id;
     private String batalhao;
     private Set areas = new HashSet(0);

    public Unidade() {
    }

	
    public Unidade(String batalhao) {
        this.batalhao = batalhao;
    }
    public Unidade(String batalhao, Set areas) {
       this.batalhao = batalhao;
       this.areas = areas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="batalhao", nullable=false, length=45)
    public String getBatalhao() {
        return this.batalhao;
    }
    
    public void setBatalhao(String batalhao) {
        this.batalhao = batalhao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidade")
    public Set getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set areas) {
        this.areas = areas;
    }




}


