package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="ocorrencia"
)
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private Rol rol;
     private int rolId;
     private String login;
     private String chave;
     private String email;
     private String funcao;
     private Boolean estado;
     private String userCriado;
     private Date dataCriado;
     private String userModificado;
     private Date dataModificado;

    public Usuario() {
    }

	
    public Usuario(Rol rol, int rolId, String login, String chave, String funcao, String userCriado, Date dataCriado) {
        this.rol = rol;
        this.rolId = rolId;
        this.login = login;
        this.chave = chave;
        this.funcao = funcao;
        this.userCriado = userCriado;
        this.dataCriado = dataCriado;
    }
    public Usuario(Rol rol, int rolId, String login, String chave, String email, String funcao, Boolean estado, String userCriado, Date dataCriado, String userModificado, Date dataModificado) {
       this.rol = rol;
       this.rolId = rolId;
       this.login = login;
       this.chave = chave;
       this.email = email;
       this.funcao = funcao;
       this.estado = estado;
       this.userCriado = userCriado;
       this.dataCriado = dataCriado;
       this.userModificado = userModificado;
       this.dataModificado = dataModificado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rol_id1", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="rol_id", nullable=false)
    public int getRolId() {
        return this.rolId;
    }
    
    public void setRolId(int rolId) {
        this.rolId = rolId;
    }

    
    @Column(name="login", nullable=false, length=45)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="chave", nullable=false, length=45)
    public String getChave() {
        return this.chave;
    }
    
    public void setChave(String chave) {
        this.chave = chave;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="funcao", nullable=false, length=45)
    public String getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }

    
    @Column(name="estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    
    @Column(name="userCriado", nullable=false, length=45)
    public String getUserCriado() {
        return this.userCriado;
    }
    
    public void setUserCriado(String userCriado) {
        this.userCriado = userCriado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataCriado", nullable=false, length=19)
    public Date getDataCriado() {
        return this.dataCriado;
    }
    
    public void setDataCriado(Date dataCriado) {
        this.dataCriado = dataCriado;
    }

    
    @Column(name="userModificado", length=45)
    public String getUserModificado() {
        return this.userModificado;
    }
    
    public void setUserModificado(String userModificado) {
        this.userModificado = userModificado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataModificado", length=19)
    public Date getDataModificado() {
        return this.dataModificado;
    }
    
    public void setDataModificado(Date dataModificado) {
        this.dataModificado = dataModificado;
    }




}


