package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Veiculo generated by hbm2java
 */
@Entity
@Table(name="veiculo"
    ,catalog="ocorrencia"
)
public class Veiculo  implements java.io.Serializable {


     private Integer placa;
     private Cidade cidade;
     private String chassi;
     private String marca;
     private String modelo;
     private Date anof;
     private Date anom;
     private String propriedade;

    public Veiculo() {
    }

	
    public Veiculo(Cidade cidade, String marca) {
        this.cidade = cidade;
        this.marca = marca;
    }
    public Veiculo(Cidade cidade, String chassi, String marca, String modelo, Date anof, Date anom, String propriedade) {
       this.cidade = cidade;
       this.chassi = chassi;
       this.marca = marca;
       this.modelo = modelo;
       this.anof = anof;
       this.anom = anom;
       this.propriedade = propriedade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="placa", unique=true, nullable=false)
    public Integer getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(Integer placa) {
        this.placa = placa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="cidade_id", referencedColumnName="id", nullable=false), 
        @JoinColumn(name="cidade_estado_id", referencedColumnName="estado_id", nullable=false), 
        @JoinColumn(name="cidade_estado_pais_id", referencedColumnName="estado_pais_id", nullable=false) } )
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="chassi", length=17)
    public String getChassi() {
        return this.chassi;
    }
    
    public void setChassi(String chassi) {
        this.chassi = chassi;
    }

    
    @Column(name="marca", nullable=false, length=45)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }

    
    @Column(name="modelo", length=45)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="anof", length=10)
    public Date getAnof() {
        return this.anof;
    }
    
    public void setAnof(Date anof) {
        this.anof = anof;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="anom", length=10)
    public Date getAnom() {
        return this.anom;
    }
    
    public void setAnom(Date anom) {
        this.anom = anom;
    }

    
    @Column(name="propriedade", length=45)
    public String getPropriedade() {
        return this.propriedade;
    }
    
    public void setPropriedade(String propriedade) {
        this.propriedade = propriedade;
    }




}


