package siop.araguaina.pojo;
// Generated 21/08/2015 15:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vtr generated by hbm2java
 */
@Entity
@Table(name="vtr"
    ,catalog="ocorrencia"
)
public class Vtr  implements java.io.Serializable {


     private int numrp;
     private String comandante;
     private String motorista;
     private String auxiliar;
     private String reforco;
     private Set registros = new HashSet(0);

    public Vtr() {
    }

	
    public Vtr(int numrp, String comandante, String motorista) {
        this.numrp = numrp;
        this.comandante = comandante;
        this.motorista = motorista;
    }
    public Vtr(int numrp, String comandante, String motorista, String auxiliar, String reforco, Set registros) {
       this.numrp = numrp;
       this.comandante = comandante;
       this.motorista = motorista;
       this.auxiliar = auxiliar;
       this.reforco = reforco;
       this.registros = registros;
    }
   
     @Id 

    
    @Column(name="numrp", unique=true, nullable=false)
    public int getNumrp() {
        return this.numrp;
    }
    
    public void setNumrp(int numrp) {
        this.numrp = numrp;
    }

    
    @Column(name="comandante", nullable=false, length=45)
    public String getComandante() {
        return this.comandante;
    }
    
    public void setComandante(String comandante) {
        this.comandante = comandante;
    }

    
    @Column(name="motorista", nullable=false, length=45)
    public String getMotorista() {
        return this.motorista;
    }
    
    public void setMotorista(String motorista) {
        this.motorista = motorista;
    }

    
    @Column(name="auxiliar", length=45)
    public String getAuxiliar() {
        return this.auxiliar;
    }
    
    public void setAuxiliar(String auxiliar) {
        this.auxiliar = auxiliar;
    }

    
    @Column(name="reforco", length=45)
    public String getReforco() {
        return this.reforco;
    }
    
    public void setReforco(String reforco) {
        this.reforco = reforco;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vtr")
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


